version: '3'

services:
  db:
    image: postgres
    ports:
    - "5432:5432"
  web:
    build: .
    command: python3 ./joplin/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/joplin
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - LOAD_DATA=off
  prisma:
    image: prismagraphql/prisma:1.7
    restart: always
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        managementApiSecret: my-server-secret-123
        port: 4466
        databases:
          default:
            connector: postgres
            host: db
            port: 5432
            user: postgres
            migrations: true
            managementSchema: management
            database: postgres
            active: true
